# Generated by Django 5.1.7 on 2025-03-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_travelrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('update', 'Update Requested'), ('closed', 'Closed'), ('deleted', 'Deleted')], max_length=20, null=True),
        ),
    ]
