# Generated by Django 5.1.7 on 2025-03-15 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_alter_travelrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='accomodation',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='manager',
        ),
        migrations.CreateModel(
            name='TravelRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('accommodation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('accommodation_type', models.CharField(blank=True, max_length=25, null=True)),
                ('travel_mode', models.CharField(choices=[('train', 'Train'), ('air', 'Air'), ('car', 'Car'), ('bus', 'Bus'), ('ship', 'Ship')], max_length=30)),
                ('purpose', models.CharField(max_length=2000)),
                ('additional_note', models.CharField(max_length=2000, null=True)),
                ('manager_note', models.CharField(max_length=2000, null=True)),
                ('admin_note', models.CharField(max_length=2000, null=True)),
                ('updatereq_asked_by_manager', models.CharField(max_length=2000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('closed', 'Closed'), ('deleted', 'Deleted')], max_length=20, null=True)),
                ('approval_date', models.DateTimeField(null=True)),
                ('rejected_date', models.DateTimeField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('resubmitted', models.BooleanField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.manager')),
            ],
        ),
        migrations.DeleteModel(
            name='Accomodation',
        ),
        migrations.DeleteModel(
            name='TravelRequest',
        ),
    ]
