# Generated by Django 5.1.7 on 2025-03-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_remove_travelrequest_accomodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='pending', max_length=20, null=True),
        ),
    ]
