# Generated by Django 4.2.17 on 2025-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_employee_last_name_travelrequests_islodging_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='travelrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
