# Generated by Django 4.2.17 on 2025-03-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_alter_manager_status_alter_travelrequests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequests',
            name='admin_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='travelrequests',
            name='manager_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='travelrequests',
            name='updatereq_asked_by_manager',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
