# Generated by Django 4.2.17 on 2025-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_alter_travelrequests_admin_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequests',
            name='updatereq_asked_by_manager',
        ),
        migrations.AlterField(
            model_name='travelrequests',
            name='additional_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='travelrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmit'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
