# Generated by Django 4.2.17 on 2025-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_remove_travelrequests_updatereq_asked_by_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequests',
            name='updatereq_asked_by_admin',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='travelrequests',
            name='updatereq_asked_by_manager',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
